In [1]:
import pandas as pd

df = pd.read_csv("98100352.csv")

In [2]:
df.to_csv("Andrew.csv")

In [3]:
df.columns

Index(['REF_DATE', 'GEO', 'DGUID', 'Age (15C)', 'Gender (3)', 'Statistics (2)',
       'Coordinate', 'Visible minority (15):Total - Visible minority[1]',
       'Symbol', 'Visible minority (15):Total visible minority population[2]',
       'Symbol.1', 'Visible minority (15):South Asian[3]', 'Symbol.2',
       'Visible minority (15):Chinese[4]', 'Symbol.3',
       'Visible minority (15):Black[5]', 'Symbol.4',
       'Visible minority (15):Filipino[6]', 'Symbol.5',
       'Visible minority (15):Arab[7]', 'Symbol.6',
       'Visible minority (15):Latin American[8]', 'Symbol.7',
       'Visible minority (15):Southeast Asian[9]', 'Symbol.8',
       'Visible minority (15):West Asian[10]', 'Symbol.9',
       'Visible minority (15):Korean[11]', 'Symbol.10',
       'Visible minority (15):Japanese[12]', 'Symbol.11',
       'Visible minority (15):Visible minority, n.i.e.[13]', 'Symbol.12',
       'Visible minority (15):Multiple visible minorities[14]', 'Symbol.13',
       'Visible minority (15):Not a visible minority[15]', 'Symbol.14'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 93960 entries, 0 to 93959
Data columns (total 37 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   REF_DATE                                                    93960 non-null  int64
 1   GEO                                                         93960 non-null  str
 2   DGUID                                                       93960 non-null  str
 3   Age (15C)                                                   93960 non-null  str
 4   Gender (3)                                                  93960 non-null  str
 5   Statistics (2)                                              93960 non-null  str
 6   Coordinate                                                  93960 non-null  str
 7   Visible minority (15):Total - Visible minority[1]           93960 non-null  float64
 8   Symbol                                                      0 non-null      float64
 9   Visible minority (15):Total visible minority population[2]  93960 non-null  float64
 10  Symbol.1                                                    0 non-null      float64
 11  Visible minority (15):South Asian[3]                        93960 non-null  float64
 12  Symbol.2                                                    0 non-null      float64
 13  Visible minority (15):Chinese[4]                            93960 non-null  float64
 14  Symbol.3                                                    0 non-null      float64
 15  Visible minority (15):Black[5]                              93960 non-null  float64
 16  Symbol.4                                                    0 non-null      float64
 17  Visible minority (15):Filipino[6]                           93960 non-null  float64
 18  Symbol.5                                                    0 non-null      float64
 19  Visible minority (15):Arab[7]                               93960 non-null  float64
 20  Symbol.6                                                    0 non-null      float64
 21  Visible minority (15):Latin American[8]                     93960 non-null  float64
 22  Symbol.7                                                    0 non-null      float64
 23  Visible minority (15):Southeast Asian[9]                    93960 non-null  float64
 24  Symbol.8                                                    0 non-null      float64
 25  Visible minority (15):West Asian[10]                        93960 non-null  float64
 26  Symbol.9                                                    0 non-null      float64
 27  Visible minority (15):Korean[11]                            93960 non-null  float64
 28  Symbol.10                                                   0 non-null      float64
 29  Visible minority (15):Japanese[12]                          93960 non-null  float64
 30  Symbol.11                                                   0 non-null      float64
 31  Visible minority (15):Visible minority, n.i.e.[13]          93960 non-null  float64
 32  Symbol.12                                                   0 non-null      float64
 33  Visible minority (15):Multiple visible minorities[14]       93960 non-null  float64
 34  Symbol.13                                                   0 non-null      float64
 35  Visible minority (15):Not a visible minority[15]            93960 non-null  float64
 36  Symbol.14                                                   0 non-null      float64
dtypes: float64(30), int64(1), str(6)
memory usage: 26.5 MB

In [6]:
df.describe()

,REF_DATE,Visible minority (15):Total - Visible minority[1],Symbol,Visible minority (15):Total visible minority population[2],Symbol.1,Visible minority (15):South Asian[3],Symbol.2,Visible minority (15):Chinese[4],Symbol.3,Visible minority (15):Black[5],...,Visible minority (15):Korean[11],Symbol.10,Visible minority (15):Japanese[12],Symbol.11,"Visible minority (15):Visible minority, n.i.e.[13]",Symbol.12,Visible minority (15):Multiple visible minorities[14],Symbol.13,Visible minority (15):Not a visible minority[15],Symbol.14
count,93960.0,9.396000e+04,0.0,9.396000e+04,0.0,9.396000e+04,0.0,9.396000e+04,0.0,9.396000e+04,...,93960.000000,0.0,93960.000000,0.0,93960.000000,0.0,93960.000000,0.0,9.396000e+04,0.0
mean,2021.0,1.224323e+04,NaN,3.322116e+03,NaN,8.942691e+02,NaN,6.014093e+02,NaN,5.130243e+02,...,76.977920,NaN,33.612099,NaN,59.731082,NaN,103.528145,NaN,8.920977e+03,NaN
std,0.0,2.493552e+05,NaN,7.057354e+04,NaN,1.971853e+04,NaN,1.327758e+04,NaN,1.105617e+04,...,1704.907105,NaN,738.260531,NaN,1403.856194,NaN,2276.825483,NaN,1.810437e+05,NaN
min,2021.0,0.000000e+00,NaN,0.000000e+00,NaN,0.000000e+00,NaN,0.000000e+00,NaN,0.000000e+00,...,0.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000e+00,NaN
25%,2021.0,0.000000e+00,NaN,0.000000e+00,NaN,0.000000e+00,NaN,0.000000e+00,NaN,0.000000e+00,...,0.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000e+00,NaN
50%,2021.0,2.500000e+01,NaN,0.000000e+00,NaN,0.000000e+00,NaN,0.000000e+00,NaN,0.000000e+00,...,0.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,NaN,2.085000e+01,NaN
75%,2021.0,2.005000e+03,NaN,7.500000e+01,NaN,1.000000e+01,NaN,0.000000e+00,NaN,1.500000e+01,...,0.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,NaN,1.855000e+03,NaN
max,2021.0,3.632848e+07,NaN,9.639200e+06,NaN,2.571400e+06,NaN,1.715775e+06,NaN,1.547865e+06,...,218135.000000,NaN,98890.000000,NaN,172885.000000,NaN,331805.000000,NaN,2.668928e+07,NaN

In [7]:
df.head()

,REF_DATE,GEO,DGUID,Age (15C),Gender (3),Statistics (2),Coordinate,Visible minority (15):Total - Visible minority[1],Symbol,Visible minority (15):Total visible minority population[2],...,Visible minority (15):Korean[11],Symbol.10,Visible minority (15):Japanese[12],Symbol.11,"Visible minority (15):Visible minority, n.i.e.[13]",Symbol.12,Visible minority (15):Multiple visible minorities[14],Symbol.13,Visible minority (15):Not a visible minority[15],Symbol.14
0,2021,Canada,2021A000011124,Total - Age,Total - Gender,2021 Counts,1.1.1.1,36328475.0,NaN,9639200.0,...,218135.0,NaN,98890.0,NaN,172885.0,NaN,331805.0,NaN,26689275.0,NaN
1,2021,Canada,2021A000011124,Total - Age,Total - Gender,% distribution (2021),1.1.1.2,100.0,NaN,26.5,...,0.6,NaN,0.3,NaN,0.5,NaN,0.9,NaN,73.5,NaN
2,2021,Canada,2021A000011124,Total - Age,Men+,2021 Counts,1.1.2.1,17937165.0,NaN,4712790.0,...,101855.0,NaN,42320.0,NaN,83305.0,NaN,160795.0,NaN,13224375.0,NaN
3,2021,Canada,2021A000011124,Total - Age,Men+,% distribution (2021),1.1.2.2,49.4,NaN,13.0,...,0.3,NaN,0.1,NaN,0.2,NaN,0.4,NaN,36.4,NaN
4,2021,Canada,2021A000011124,Total - Age,Women+,2021 Counts,1.1.3.1,18391310.0,NaN,4926415.0,...,116280.0,NaN,56575.0,NaN,89575.0,NaN,171015.0,NaN,13464900.0,NaN

In [10]:
filtered_columns = ['REF_DATE', 'GEO', 'DGUID', 'Age (15C)', 'Gender (3)', 'Statistics (2)',
        'Visible minority (15):Total - Visible minority[1]',
        'Visible minority (15):Total visible minority population[2]',
       'Visible minority (15):South Asian[3]',
       'Visible minority (15):Chinese[4]',
       'Visible minority (15):Black[5]',
       'Visible minority (15):Filipino[6]',
       'Visible minority (15):Arab[7]',
       'Visible minority (15):Latin American[8]',
       'Visible minority (15):Southeast Asian[9]',
       'Visible minority (15):West Asian[10]',
       'Visible minority (15):Korean[11]',
       'Visible minority (15):Japanese[12]',
       'Visible minority (15):Visible minority, n.i.e.[13]',
       'Visible minority (15):Multiple visible minorities[14]',
       'Visible minority (15):Not a visible minority[15]']

filtered_scenarios = ['% distribution (2021)']
filtered_scenarios1 = ['Total - Gender']
filtered_scenarios2 = ['Total - Age']

df_filtered = df[filtered_columns]

df_filtered = df_filtered[df_filtered["Statistics (2)"].isin(filtered_scenarios)]
df_filtered = df_filtered[df_filtered["Gender (3)"].isin(filtered_scenarios1)]
df_filtered = df_filtered[df_filtered["Age (15C)"].isin(filtered_scenarios2)]

In [11]:
df_filtered.rename(columns={
    "Age (15C)": "Age",
    "Gender (3)": "Gender",
    "Statistics (2)": "Statistics",
    "Visible minority (15):Total - Visible minority[1]": "Total - Minority",
    "Visible minority (15):Total visible minority population[2]": "Total Minority Population",
    "Visible minority (15):South Asian[3]": "South Asian",
    "Visible minority (15):Chinese[4]": "Chinese",
    "Visible minority (15):Black[5]": "Black",
    "Visible minority (15):Filipino[6]": "Filipino",
    "Visible minority (15):Arab[7]": "Arab",
    "Visible minority (15):Latin American[8]": "Latin American",
    "Visible minority (15):Southeast Asian[9]": "Southeast Asian",
    "Visible minority (15):West Asian[10]": "West Asian",
    "Visible minority (15):Korean[11]": "Korean",
    "Visible minority (15):Japanese[12]": "Japanese",
    "Visible minority (15):Visible minority, n.i.e.[13]": "Minority, n.i.e",
    "Visible minority (15):Multiple visible minorities[14]": "Multiple Minorities",
    "Visible minority (15):Not a visible minority[15]": "Not Minority"

    
}, inplace=True)
df_filtered.head()

,REF_DATE,GEO,DGUID,Age,Gender,Statistics,Total - Minority,Total Minority Population,South Asian,Chinese,...,Filipino,Arab,Latin American,Southeast Asian,West Asian,Korean,Japanese,"Minority, n.i.e",Multiple Minorities,Not Minority
1,2021,Canada,2021A000011124,Total - Age,Total - Gender,% distribution (2021),100.0,26.5,7.1,4.7,...,2.6,1.9,1.6,1.1,1.0,0.6,0.3,0.5,0.9,73.5
91,2021,Newfoundland and Labrador,2021A000210,Total - Age,Total - Gender,% distribution (2021),1.4,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.3
181,2021,Division No. 1 (1001),2021A00031001,Total - Age,Total - Gender,% distribution (2021),0.7,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7
271,2021,Bay Roberts (1001409) T,2021A00051001409,Total - Age,Total - Gender,% distribution (2021),0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
361,2021,Conception Bay South (1001485) T,2021A00051001485,Total - Age,Total - Gender,% distribution (2021),0.1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1

In [12]:
df_filtered.duplicated()
df_filtered_clean = df_filtered.drop_duplicates()
df_filtered.head()

,REF_DATE,GEO,DGUID,Age,Gender,Statistics,Total - Minority,Total Minority Population,South Asian,Chinese,...,Filipino,Arab,Latin American,Southeast Asian,West Asian,Korean,Japanese,"Minority, n.i.e",Multiple Minorities,Not Minority
1,2021,Canada,2021A000011124,Total - Age,Total - Gender,% distribution (2021),100.0,26.5,7.1,4.7,...,2.6,1.9,1.6,1.1,1.0,0.6,0.3,0.5,0.9,73.5
91,2021,Newfoundland and Labrador,2021A000210,Total - Age,Total - Gender,% distribution (2021),1.4,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.3
181,2021,Division No. 1 (1001),2021A00031001,Total - Age,Total - Gender,% distribution (2021),0.7,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7
271,2021,Bay Roberts (1001409) T,2021A00051001409,Total - Age,Total - Gender,% distribution (2021),0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
361,2021,Conception Bay South (1001485) T,2021A00051001485,Total - Age,Total - Gender,% distribution (2021),0.1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1

In [13]:
df_filtered.to_csv('Andrew.csv', index=False)